#!/usr/bin/env bash
# 10-fizzbuzz
for i in {1..100}; do
  if [ $((i % 15)) -eq 0 ]; then
    out="FizzBuzz"
  elif [ $((i % 3)) -eq 0 ]; then
    out="Fizz"
  elif [ $((i % 5)) -eq 0 ]; then
    out="Buzz"
  else
    out="$i"
  fi

  if [ "$i" -ne 100 ]; then
    echo -n "$out "
  else
    echo "$out"
  fi
done
