#!/usr/bin/env bash
# 10-fizzbuzz
for i in {1..100}; do
  if [ $((i % 15)) -eq 0 ]; then
    printf "FizzBuzz "
  elif [ $((i % 3)) -eq 0 ]; then
    printf "Fizz "
  elif [ $((i % 5)) -eq 0 ]; then
    printf "Buzz "
  else
    printf "%s " "$i"
  fi
done
echo
